apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
#- name: ghcr.io/shclub/edu12-backend
- name: ghcr.io/dragorse/edu12-backend
  newTag: "20230322092639"
#- name: shclub/edu12-backend
#  newTag: "20230322080446"
